# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='club',
        ),
    ]
