# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20170309_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.URLField(),
        ),
    ]
